# Generated by Django 4.0.4 on 2022-11-20 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknow', max_length=255)),
                ('store_emp_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('quantity_sold', models.IntegerField()),
                ('left', models.IntegerField()),
                ('price', models.IntegerField()),
                ('summ', models.IntegerField()),
                ('truck', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='sklad_core.truck')),
            ],
        ),
    ]
