# Generated by Django 4.0.4 on 2022-11-21 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sklad_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='truck',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sklad_core.truck'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='store_emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
