# Generated by Django 4.0.4 on 2022-11-21 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_core', '0002_alter_product_truck_alter_truck_store_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad_core.truck'),
        ),
    ]
