# Generated by Django 4.0.4 on 2022-11-21 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sklad_core', '0004_alter_product_truck_alter_truck_store_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='name',
            field=models.CharField(default='unknow', max_length=255, verbose_name='Truck nomi'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='store_emp_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Truck xodimi'),
        ),
    ]
