# Generated by Django 4.0.4 on 2022-11-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_core', '0008_infobydate_year_alter_infobydate_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Ovqat', 'Ovqat'), ('Suv', 'Suv')], max_length=8, null=True),
        ),
    ]
