# Generated by Django 4.0.4 on 2022-11-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_core', '0009_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Ovqat', 'Ovqat'), ('Suv', 'Suv')], default='Ovqat', max_length=8, null=True),
        ),
    ]
