# Generated by Django 4.0.4 on 2022-11-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_core', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='defect',
            field=models.IntegerField(default=0),
        ),
    ]
