# Generated by Django 4.0.4 on 2022-11-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_core', '0011_product_defect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infobydate',
            name='emp_expenses',
        ),
        migrations.AddField(
            model_name='infobydate',
            name='cleaners',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infobydate',
            name='cookers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infobydate',
            name='ffcookers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infobydate',
            name='sellers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infobydate',
            name='somsapazlar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infobydate',
            name='suvchilar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infobydate',
            name='unecomment',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
