# Generated by Django 4.0.4 on 2022-11-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_core', '0012_remove_infobydate_emp_expenses_infobydate_cleaners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra',
            field=models.IntegerField(default=0),
        ),
    ]
