# Generated by Django 4.0.4 on 2022-11-28 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_core', '0013_product_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='infobydate',
            name='page',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='infobydate',
            name='unecomment',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('year', models.CharField(max_length=16, null=True)),
                ('month', models.CharField(max_length=128, null=True)),
                ('page', models.TextField(default='')),
                ('comment', models.TextField(default='')),
                ('archive_truck_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='sklad_core.truck')),
            ],
        ),
    ]
