# Generated by Django 4.0.4 on 2022-11-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_core', '0014_infobydate_page_alter_infobydate_unecomment_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='infobydate',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='infobydate',
            name='cleaners',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='infobydate',
            name='cookers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='infobydate',
            name='ffcookers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='infobydate',
            name='sellers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='infobydate',
            name='somsapazlar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='infobydate',
            name='suvchilar',
            field=models.IntegerField(),
        ),
    ]
