# Generated by Django 4.0.4 on 2022-11-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_core', '0015_infobydate_day_alter_infobydate_cleaners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='yest_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='infobydate',
            name='date',
            field=models.DateField(),
        ),
    ]
